my_list = ['New York', 'London', 'Seul', 'Tokyo', 'Paris']
# print(my_list)
# print(sorted(my_list))
# print(my_list)
# my_list.reverse()
# print(my_list)
# my_list.reverse()
# print(my_list)
# my_list.sort()
# print(my_list)
# my_list.sort(reverse=True)
# print(my_list)
print(len(my_list))
